name: Update GPU driver

on:
  schedule:
    - cron:  '0 3 * * 2'
  pull_request:
    branches:
    - sycl
    paths:
    - .github/workflows/sycl_update_gpu_driver.yml
  workflow_dispatch:

jobs:
  update_driver_linux:
    runs-on: ubuntu-latest
    if: github.repository == 'intel/llvm'
    steps:
    - uses: actions/checkout@v2
    - name: Update dependencies file
      run: |
        version="$(python3 devops/scripts/update_drivers.py linux)"
        echo 'NEW_DRIVER_VERSION='$version >> $GITHUB_ENV
    - name: Create Pull Request
      env:
        BRANCH: ci/update_gpu_driver-linux-${{ env.NEW_DRIVER_VERSION }}
        GITHUB_TOKEN: ${{ secrets.LLVM_MAIN_SYNC_BBSYCL_TOKEN }}
      run: |
        cd $GITHUB_WORKSPACE
        git config --global user.name "Buildbot for SYCL"
        git config --global user.email "bb-sycl@github.com"
        git checkout -B $BRANCH
        git add -u
        git commit -m "[GHA] Uplift Linux GPU RT version to $NEW_DRIVER_VERSION" || exit 0   # exit if commit is empty
        echo AAAA
        echo ${#GITHUB_TOKEN}
        echo AAAAAA
        git push https://$GITHUB_TOKEN@github.com/${{ github.repository }} ${BRANCH}
        echo BBBB
        gh pr create --head $BRANCH --title "[GHA] Uplift GPU RT version for Linux CI" --body "Uplift GPU RT version for Linux to $NEW_DRIVER_VERSION"
        echo CCCC
